from pathlib import Path
import streamlit as st
import pandas as pd
import plotly.express as px

from utils.styles import load_css

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="Executive Dashboard",
    page_icon="🏢",
    layout="wide"
)

st.markdown(
    load_css(),
    unsafe_allow_html=True
)

# =====================================================
# FILE PATHS
# =====================================================

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs"

# =====================================================
# LOAD DATA
# =====================================================

try:

    df = pd.read_csv(
        OUTPUT_DIR / "risk_scores.csv"
    )

except Exception as e:

    st.error(
        f"Unable to load risk_scores.csv: {e}"
    )

    st.stop()

# =====================================================
# PREP DATA
# =====================================================

investable = df[
    df["Recommendation"] != "LOW LIQUIDITY"
].copy()

avg_risk = round(
    investable["Risk_Score"].mean(),
    1
)

highest_risk_security = (
    investable
    .sort_values(
        "Risk_Score",
        ascending=False
    )
    .iloc[0]
)

low_risk_count = len(
    investable[
        investable["Recommendation"]
        == "LOW VOLATILITY RISK"
    ]
)

moderate_risk_count = len(
    investable[
        investable["Recommendation"]
        == "MODERATE VOLATILITY RISK"
    ]
)

high_risk_count = len(
    investable[
        investable["Recommendation"]
        == "HIGH VOLATILITY RISK"
    ]
)

low_liquidity_count = len(
    df[
        df["Recommendation"]
        == "LOW LIQUIDITY"
    ]
)

# =====================================================
# PAGE TITLE
# =====================================================

st.title("🏢 Executive Dashboard")

st.markdown(
    """
Executive overview of market volatility,
risk concentration and security-level
intelligence generated by FinSight AI.
"""
)

# =====================================================
# EXECUTIVE MARKET STATUS
# =====================================================

st.subheader("Market Risk Status")

if avg_risk <= 33:

    st.success(
        f"""
### 🟢 LOW RISK MARKET ENVIRONMENT

**Average Market Risk Score:** {avg_risk}/100
"""
    )

elif avg_risk <= 65:

    st.warning(
        f"""
### 🟡 MODERATE RISK MARKET ENVIRONMENT

**Average Market Risk Score:** {avg_risk}/100
"""
    )

else:

    st.error(
        f"""
### 🔴 HIGH RISK MARKET ENVIRONMENT

**Average Market Risk Score:** {avg_risk}/100
"""
    )

# =====================================================
# MARKET SNAPSHOT
# =====================================================

st.header("Market Snapshot")

c1, c2, c3 = st.columns(3)

with c1:

    st.metric(
        "Average Risk Score",
        f"{avg_risk}/100"
    )

with c2:

    st.metric(
        "Highest Risk Security",
        highest_risk_security["Name"]
    )

with c3:

    st.metric(
        "Securities Covered",
        len(df)
    )

st.divider()

# =====================================================
# SECURITIES REQUIRING ATTENTION
# =====================================================

st.header("🚨 Securities Requiring Immediate Attention")

high_risk = (
    investable
    .sort_values(
        "Risk_Score",
        ascending=False
    )
    .head(10)
)

st.dataframe(
    high_risk[
        [
            "Volatility_Rank",
            "Code",
            "Name",
            "Risk_Score"
        ]
    ],
    use_container_width=True
)

st.divider()
# =====================================================
# RISK CLASSIFICATION OVERVIEW
# =====================================================

st.header("Risk Classification Overview")

c1, c2, c3, c4 = st.columns(4)

with c1:

    st.metric(
        "Low Volatility Risk",
        low_risk_count
    )

with c2:

    st.metric(
        "Moderate Volatility Risk",
        moderate_risk_count
    )

with c3:

    st.metric(
        "High Volatility Risk",
        high_risk_count
    )

with c4:

    st.metric(
        "Low Liquidity",
        low_liquidity_count
    )

st.divider()

# =====================================================
# MARKET RISK DISTRIBUTION
# =====================================================

st.header("Market Risk Distribution")

distribution = (
    df["Recommendation"]
    .value_counts()
    .reset_index()
)

distribution.columns = [
    "Risk Category",
    "Count"
]

fig = px.bar(
    distribution,
    x="Count",
    y="Risk Category",
    orientation="h",
    text="Count",
    title="Distribution of Securities by Risk Classification"
)

fig.update_layout(
    height=500,
    yaxis_title="",
    xaxis_title="Number of Securities",
    showlegend=False
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()

# =====================================================
# EXECUTIVE ASSESSMENT
# =====================================================

st.header("Executive Assessment")

top_high_risk = (
    investable
    .sort_values(
        "Risk_Score",
        ascending=False
    )
    .head(5)
)

top_names = ", ".join(
    top_high_risk["Code"]
)

if avg_risk <= 33:
    market_condition = "low-risk"

elif avg_risk <= 65:
    market_condition = "moderate-risk"

else:
    market_condition = "high-risk"

commentary = f"""
### Executive Summary

The market is currently operating within a
**{market_condition} environment** with an
average risk score of **{avg_risk}/100**.

A total of **{high_risk_count} securities**
are currently classified as High Volatility Risk
and require enhanced management attention.

The highest-risk securities currently include:

**{top_names}**

These securities exhibit elevated forecast
volatility relative to the broader market and
should remain under close observation.

Overall market conditions remain manageable,
although concentrated pockets of risk continue
to exist within selected securities.
"""

st.info(commentary)

st.divider()

# =====================================================
# STRATEGIC ACTIONS
# =====================================================

st.header("Strategic Actions")

st.error(
    f"""
Review and closely monitor
{high_risk_count} High Volatility Risk
securities.
"""
)

st.warning(
    f"""
Maintain active surveillance on
{moderate_risk_count} Moderate Volatility Risk
securities.
"""
)

st.success(
    f"""
Consider the
{low_risk_count} Low Volatility Risk
securities for defensive portfolio
positioning.
"""
)

st.divider()

# =====================================================
# LOWEST VOLATILITY OPPORTUNITIES
# =====================================================

st.header("🟢 Lowest Volatility Opportunities")

low_risk = (
    investable
    .sort_values(
        "Risk_Score",
        ascending=True
    )
    .head(10)
)

st.dataframe(
    low_risk[
        [
            "Volatility_Rank",
            "Code",
            "Name",
            "Risk_Score"
        ]
    ],
    use_container_width=True
)

st.divider()

# =====================================================
# FULL RISK REGISTER
# =====================================================

st.header("Full Risk Register")

st.dataframe(
    investable.sort_values(
        "Risk_Score",
        ascending=False
    ),
    use_container_width=True,
    height=600
)

# =====================================================
# METHODOLOGY
# =====================================================

with st.expander(
    "View Risk Classification Methodology"
):

    st.info(
        """
LOW VOLATILITY RISK

Risk Score ≤ 33

MODERATE VOLATILITY RISK

Risk Score > 33 and ≤ 65

HIGH VOLATILITY RISK

Risk Score > 65

LOW LIQUIDITY

Insufficient trading activity for reliable
volatility assessment.
"""
    )

# =====================================================
# FOOTER
# =====================================================

st.caption(
    "FinSight AI • Executive Dashboard • Volatility Risk Intelligence Platform"
)